FROM node:20-buster as build
WORKDIR /app
ADD . ./
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run build

FROM nginx:alpine

RUN apk add -U tzdata
ENV TZ=America/Mexico_City
RUN cp /usr/share/zoneinfo/America/Mexico_City /etc/localtime

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]